/*! Teaching bank: syntax + code + when/why + docs/videos for every major concept */
window.TEACH_BANK = {
  topics: {
    gccTools: {
      keys: ["gcc", "xcode", "tools check", "python3 --version", "command line tools"],
      why: "Without a compiler and Python, you cannot practice C or build NetKV/DSA labs on this machine.",
      idea: "gcc turns C source text into a runnable binary. python3 runs scripts and servers. On macOS, gcc usually comes from Command Line Tools (small install), not the full Xcode app.",
      when: "New laptop setup, after OS updates, before any CMSC 216 work.",
      syntax: "gcc --version\npython3 --version\nxcode-select --install   # only if gcc missing\nmkdir -p ~/umd-prep/cmsc216",
      code: "# nothing to compile yet — you are verifying tools\n# After install, this should print versions, not 'command not found'",
      walkthrough: "1) Open Terminal\n2) gcc --version\n3) python3 --version\n4) If gcc fails, run xcode-select --install and wait\n5) Create umd-prep folders",
      bugs: "command not found: gcc → install CLT. python3 missing → python.org installer. Permission errors on mkdir → check path typo.",
      resources: [
        { label: "Guide: How C programs run", url: "guides/how-c-programs-run.html", use: "Read fully" },
        { label: "Command Line Tools explained", url: "https://mac.install.guide/commandlinetools/index.html", use: "Only if gcc missing" },
        { label: "Python downloads", url: "https://www.python.org/downloads/", use: "If python3 missing" },
      ],
    },
    cCompile: {
      keys: ["hello.c", "compile", "sizeof", "first c program", "-wall", "warned c"],
      why: "CMSC 216 is C. You must know compile vs run, warnings, and sizeof before pointers.",
      idea: "A .c file is text. gcc compiles it to a binary. You run ./binary. -Wall -Wextra surface mistakes. sizeof(type) is bytes on THIS machine. main is the entry point.",
      when: "Every 216 lab, any C systems work, debugging 'I ran the .c file' mistakes.",
      syntax: "#include <stdio.h>\n\nint main(void) {\n  printf(\"hi\\n\");\n  printf(\"%zu\\n\", sizeof(int));\n  return 0;\n}\n\n# build + run:\ngcc -Wall -Wextra -o hello hello.c\n./hello",
      code: "#include <stdio.h>\n\nint main(void) {\n  printf(\"Abhy\\n\");\n  printf(\"int=%zu long=%zu ptr=%zu\\n\",\n         sizeof(int), sizeof(long), sizeof(char*));\n  return 0;\n}",
      walkthrough: "Write hello.c → gcc -Wall -Wextra -o hello hello.c → ./hello → read sizes. int often 4, pointers often 8 on modern Macs.",
      bugs: "expected ';' → look at line above. unused variable warning → delete/use it. ./hello permission → compile with -o hello first. running hello.c directly does nothing useful.",
      resources: [
        { label: "Guide: How C programs run", url: "guides/how-c-programs-run.html", use: "Before coding" },
        { label: "Beej Guide to C", url: "https://beej.us/guide/bgc/", use: "Skim intro + hello" },
        { label: "GCC warning options", url: "https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html", use: "What -Wall means" },
        { label: "CS50 C short (video)", url: "https://www.youtube.com/watch?v=3lQNi5ga7ZQ", use: "Broader C mental model" },
      ],
    },
    cArrays: {
      keys: ["array lab", "arrays.c", "contiguous", "a[10]"],
      why: "Arrays are how C stores sequences. Indexing is address arithmetic — required for 216 and interview mental models.",
      idea: "int a[10] reserves 10 ints in a row. a[i] is like *(a+i). &a[i+1] is typically sizeof(int) bytes after &a[i].",
      when: "216 labs, buffers, strings (char arrays), explaining memory layout.",
      syntax: "int a[10];\nfor (int i = 0; i < 10; i++) a[i] = i;\nprintf(\"%d %p\\n\", a[0], (void*)&a[0]);",
      code: "#include <stdio.h>\n\nint main(void) {\n  int a[10];\n  for (int i = 0; i < 10; i++) a[i] = i;\n  for (int i = 0; i < 10; i++)\n    printf(\"%d \", a[i]);\n  printf(\"\\n\");\n  printf(\"&a[0]=%p &a[1]=%p\\n\", (void*)&a[0], (void*)&a[1]);\n  return 0;\n}",
      walkthrough: "Fill 0..9 → print values → print &a[0] and &a[1] → subtract addresses mentally (should be 4 if int is 4 bytes).",
      bugs: "Writing past a[9] is undefined behavior. %p needs (void*). Forgetting -Wall hides issues.",
      resources: [
        { label: "Beej arrays/pointers", url: "https://beej.us/guide/bgc/html/split/arrays.html", use: "Read arrays section" },
        { label: "CS50 arrays (video)", url: "https://www.youtube.com/watch?v=7mORC3avlqU", use: "Visual mental model" },
      ],
    },
    pointers: {
      keys: ["pointer", "cs50 pointers", "ptr_lab", "*p", "dereference", "pointiers"],
      why: "Pointers are the core of CMSC 216. Without them, malloc, strings, and data structures do not make sense.",
      idea: "Every variable lives at an address. &x is that address. int *p stores an address of an int. *p reads/writes the value at that address. Declaration int *p ≠ expression *p.",
      when: "Almost every 216 assignment, swap, strings as char*, linked structures, interview pass-by-pointer.",
      syntax: "int x = 42;\nint *p = &x;   /* p holds address of x */\nprintf(\"%d\\n\", *p); /* follow pointer → 42 */\n*p = 7;            /* writes into x */",
      code: "#include <stdio.h>\n\nint main(void) {\n  int x = 42;\n  int *p = &x;\n  printf(\"x=%d &x=%p p=%p *p=%d\\n\", x, (void*)&x, (void*)p, *p);\n  *p = 7;\n  printf(\"after *p=7, x=%d\\n\", x);\n  return 0;\n}",
      walkthrough: "Draw boxes for x and p. Arrow from p to x. Show *p=7 changing x.",
      bugs: "segfault → * on NULL/garbage. Mixing up int* declaration with dereference. Passing ints to swap instead of &x.",
      resources: [
        { label: "Guide: Pointers in C", url: "guides/pointers-in-c.html", use: "Read fully first" },
        { label: "CS50 pointers lecture", url: "https://www.youtube.com/watch?v=XISnO2YhQ-A", use: "Watch with notes" },
        { label: "Beej pointers chapter", url: "https://beej.us/guide/bgc/html/split/pointers.html", use: "Re-read after video" },
      ],
    },
    swapStrlen: {
      keys: ["swap", "my_strlen", "pass by pointer"],
      why: "Shows why C needs pointers to mutate caller data, and how C-strings end in '\\0'.",
      idea: "swap(int a,int b) swaps copies. swap(int *a,int *b) can write through addresses. strlen walks bytes until '\\0'.",
      when: "216 string labs, APIs that mutate outputs via pointers, interview warmups.",
      syntax: "void swap(int *a, int *b) {\n  int t = *a; *a = *b; *b = t;\n}\n\nsize_t my_strlen(const char *s) {\n  size_t n = 0;\n  while (s[n] != '\\0') n++;\n  return n;\n}",
      code: "#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n  int t = *a; *a = *b; *b = t;\n}\n\nint main(void) {\n  int x = 3, y = 5;\n  swap(&x, &y);\n  printf(\"%d %d\\n\", x, y); /* 5 3 */\n  return 0;\n}",
      walkthrough: "Call swap(&x,&y). Inside, *a and *b are x and y. Trace one iteration of my_strlen on \"hi\".",
      bugs: "Forgetting & when calling swap. Infinite loop in strlen if missing '\\0'. Modifying const string literals.",
      resources: [
        { label: "Guide: Pointers in C", url: "guides/pointers-in-c.html", use: "Swap section" },
        { label: "Beej pointers", url: "https://beej.us/guide/bgc/html/split/pointers.html", use: "Practice problems mindset" },
      ],
    },
    gdb: {
      keys: ["gdb", "breakpoint", "backtrace"],
      why: "Print-debugging lies. gdb lets you stop and inspect real state — critical in 216.",
      idea: "Compile with -g. gdb ./prog → break main → run → next/step → print var → backtrace on crash.",
      when: "Segfaults, wrong values, any non-trivial C bug.",
      syntax: "gcc -g -Wall -o lab lab.c\ngdb ./lab\n(gdb) break main\n(gdb) run\n(gdb) next\n(gdb) print x\n(gdb) backtrace",
      code: "/* intentional bug example */\nint *p = 0;\n*p = 1; /* crash: examine with gdb */",
      walkthrough: "Build -g → break main → run → next until interesting line → print locals → fix code → recompile.",
      bugs: "No debug symbols → forgot -g. Optimized away variables → use -O0 while debugging.",
      resources: [
        { label: "GDB sample session", url: "https://sourceware.org/gdb/current/onlinedocs/gdb.html/Sample-Session.html", use: "Official walkthrough" },
        { label: "GDB tutorial video", url: "https://www.youtube.com/watch?v=PorfLSr3DDI", use: "Watch once, then do" },
        { label: "GDB cheat sheet", url: "https://darkdust.net/files/GDB%20Cheat%20Sheet.pdf", use: "Keep open while debugging" },
      ],
    },
    malloc: {
      keys: ["malloc", "heap", "free(", "heap_lab"],
      why: "Stack locals die when functions return. Heap memory lasts until free — needed for dynamic sizes.",
      idea: "malloc(n) returns a pointer to n bytes (or NULL). You must free it. Check NULL. Size usually n * sizeof(T).",
      when: "Dynamic arrays, 216 projects, understanding leaks and use-after-free.",
      syntax: "int *a = malloc(n * sizeof(int));\nif (!a) { /* handle OOM */ return 1; }\n...\nfree(a);",
      code: "#include <stdio.h>\n#include <stdlib.h>\n\nint main(int argc, char **argv) {\n  if (argc < 2) return 1;\n  int n = atoi(argv[1]);\n  int *a = malloc((size_t)n * sizeof(int));\n  if (!a) return 1;\n  for (int i = 0; i < n; i++) a[i] = i;\n  for (int i = 0; i < n; i++) printf(\"%d \", a[i]);\n  printf(\"\\n\");\n  free(a);\n  return 0;\n}",
      walkthrough: "atoi argv → malloc → fill → print → free. Run with ./heap_lab 5.",
      bugs: "Forgetting free (leak). Using after free. Not checking NULL. Wrong byte size (forgot sizeof).",
      resources: [
        { label: "malloc(3) man page", url: "https://man7.org/linux/man-pages/man3/malloc.3.html", use: "Read DESCRIPTION + RETURN" },
        { label: "CS50 memory (video)", url: "https://www.youtube.com/watch?v=cNKH4MFKBxs", use: "Heap vs stack visuals" },
      ],
    },
    structs: {
      keys: ["struct", "point", "p->"],
      why: "Real programs group related fields. Pointers to structs are how you pass/mutate them efficiently.",
      idea: "struct Point { int x; int y; }; packs fields. p->x means (*p).x.",
      when: "216 data modeling, game entities, network packets, any grouped state.",
      syntax: "struct Point { int x; int y; };\nvoid move(struct Point *p, int dx, int dy) {\n  p->x += dx;\n  p->y += dy;\n}",
      code: "#include <stdio.h>\n\nstruct Point { int x; int y; };\n\nvoid move(struct Point *p, int dx, int dy) {\n  p->x += dx;\n  p->y += dy;\n}\n\nint main(void) {\n  struct Point pt = {0, 0};\n  move(&pt, 2, 3);\n  printf(\"%d %d\\n\", pt.x, pt.y);\n  return 0;\n}",
      walkthrough: "Create pt → move(&pt,2,3) → print 2 3.",
      bugs: "Using . on a pointer (need ->). Passing struct by value accidentally when you meant pointer.",
      resources: [
        { label: "Beej structs", url: "https://beej.us/guide/bgc/html/split/structs.html", use: "Read structs chapter" },
        { label: "C structs (video)", url: "https://www.youtube.com/watch?v=qWJpI2KZy3c", use: "Quick syntax pass" },
      ],
    },
    hashmap: {
      keys: ["dict", "hash map", "hashing", "roadmap", "arrays and hashing"],
      why: "Hash maps turn many O(n^2) scans into O(n). Core interview pattern and real caching.",
      idea: "dict/map: key → value, average O(1) get/set. Use when you keep asking 'have I seen X?' or 'what index was X?'.",
      when: "Two Sum family, anagrams, duplicates, API caches, counting.",
      syntax: "seen = {}\nseen[2] = 0\nif 7 in seen:\n    print(seen[7])\nprint(seen.get(99))  # None",
      code: "seen = {}\nfor i, x in enumerate([2, 7, 11]):\n    seen[x] = i\nprint(seen)  # {2:0, 7:1, 11:2}",
      walkthrough: "Create empty dict → store values as you go → lookup complement in O(1).",
      bugs: "Unhashable key (list). Forgetting to store. Confusing 'in dict' (keys) with 'in dict.values()'.",
      resources: [
        { label: "Guide: Hash maps and Two Sum", url: "guides/hash-maps-and-two-sum.html", use: "Read fully" },
        { label: "Python dict docs", url: "https://docs.python.org/3/tutorial/datastructures.html#dictionaries", use: "Syntax reference" },
        { label: "Hash table explainer (video)", url: "https://www.youtube.com/watch?v=shs0yu1-PtA", use: "Broader concept" },
        { label: "NeetCode roadmap", url: "https://neetcode.io/roadmap", use: "See Arrays & Hashing order" },
      ],
    },
    twoSum: {
      keys: ["two sum", "two_sum", "01_two_sum"],
      why: "Classic interview Easy. Forces the hash-map complement pattern.",
      idea: "For each x, need target-x. If need already seen, return indices. Else store x→i.",
      when: "Any pair-with-sum problem; template for many hash questions.",
      syntax: "def two_sum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        need = target - x\n        if need in seen:\n            return [seen[need], i]\n        seen[x] = i",
      code: "def two_sum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        need = target - x\n        if need in seen:\n            return [seen[need], i]\n        seen[x] = i\n\nassert two_sum([2,7,11,15], 9) == [0,1]",
      walkthrough: "[2,7,11], target 9 → store 2→0 → at 7 need 2 found → [0,1]",
      bugs: "Returning values not indices. Using same element twice. Pasting without being able to rewrite.",
      resources: [
        { label: "Guide: Hash maps and Two Sum", url: "guides/hash-maps-and-two-sum.html", use: "Before coding" },
        { label: "LeetCode Two Sum", url: "https://leetcode.com/problems/two-sum/", use: "Submit after you understand" },
        { label: "NeetCode Two Sum video", url: "https://www.youtube.com/watch?v=KLlXCFG5TnA", use: "Only if stuck 15+ min, then rewrite" },
      ],
    },
    containsDup: {
      keys: ["contains duplicate", "contains_duplicate", "duplicate"],
      why: "Set membership is the simplest hash pattern after Two Sum.",
      idea: "Scan; if value already in a set, duplicate exists; else add it.",
      when: "Deduping, uniqueness checks, interview Easy warmups.",
      syntax: "def contains_duplicate(nums):\n    seen = set()\n    for n in nums:\n        if n in seen:\n            return True\n        seen.add(n)\n    return False",
      code: "assert contains_duplicate([1,2,3,1]) is True\nassert contains_duplicate([1,2,3]) is False",
      walkthrough: "[1,2,3,1] → add 1,2,3 → second 1 hits set → True",
      bugs: "Using list instead of set (O(n) 'in'). Sorting approach is fine but know the set version.",
      resources: [
        { label: "LeetCode Contains Duplicate", url: "https://leetcode.com/problems/contains-duplicate/", use: "Practice" },
        { label: "Python set docs", url: "https://docs.python.org/3/tutorial/datastructures.html#sets", use: "Syntax" },
        { label: "NeetCode Contains Duplicate", url: "https://www.youtube.com/watch?v=3OamzN90kPg", use: "If stuck" },
      ],
    },
    anagram: {
      keys: ["anagram", "valid anagram", "group anagram"],
      why: "Counting / sorting as keys teaches hash signatures.",
      idea: "Anagrams share letter counts. Count with dict/array, or sort string as map key for grouping.",
      when: "String interview problems, grouping records by signature.",
      syntax: "from collections import Counter\nCounter('an') == Counter('na')  # True\n\n# group key:\nkey = ''.join(sorted(word))",
      code: "def is_anagram(s, t):\n    if len(s) != len(t): return False\n    count = [0]*26\n    for ch in s: count[ord(ch)-97] += 1\n    for ch in t: count[ord(ch)-97] -= 1\n    return all(c == 0 for c in count)",
      walkthrough: "Valid Anagram: count s up, t down, all zero. Group Anagrams: map sorted(word) → list of words.",
      bugs: "Unicode assumptions. Using list as dict key (use tuple of counts or sorted string).",
      resources: [
        { label: "Valid Anagram", url: "https://leetcode.com/problems/valid-anagram/", use: "Solve" },
        { label: "Group Anagrams", url: "https://leetcode.com/problems/group-anagrams/", use: "Next pattern" },
        { label: "NeetCode Valid Anagram", url: "https://www.youtube.com/watch?v=9UtInBqnCgA", use: "If stuck" },
      ],
    },
    twoPointers: {
      keys: ["palindrome", "two pointer", "container", "buy and sell", "buy_sell", "stock"],
      why: "Two pointers / one-pass tracking removes nested loops on sorted or linear scans.",
      idea: "Left/right indices move toward a goal, OR track a running min/best while scanning once.",
      when: "Palindromes, container water, best time to buy/sell, many array Easy/Mediums.",
      syntax: "# palindrome style\nl, r = 0, len(s)-1\nwhile l < r:\n    # skip junk, compare s[l] s[r]\n    l += 1; r -= 1\n\n# stock style\nmin_price = float('inf')\nbest = 0\nfor p in prices:\n    min_price = min(min_price, p)\n    best = max(best, p - min_price)",
      code: "def max_profit(prices):\n    min_price = float('inf')\n    best = 0\n    for p in prices:\n        if p < min_price: min_price = p\n        best = max(best, p - min_price)\n    return best",
      walkthrough: "Stock [7,1,5,3,6,4]: min becomes 1, best peaks at 5 (6-1).",
      bugs: "Off-by-one on indices. Updating min after profit incorrectly. Forgetting to skip non-alnum in palindrome.",
      resources: [
        { label: "Best Time to Buy/Sell Stock", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", use: "One-pass pattern" },
        { label: "Valid Palindrome", url: "https://leetcode.com/problems/valid-palindrome/", use: "Two pointers" },
        { label: "Container With Most Water", url: "https://leetcode.com/problems/container-with-most-water/", use: "Two pointers medium" },
        { label: "NeetCode stock video", url: "https://www.youtube.com/watch?v=1pkOgXD63VM", use: "If stuck" },
      ],
    },
    slidingWindow: {
      keys: ["longest substring", "sliding window", "window"],
      why: "Variable window is the next hashing+two-pointers hybrid — common Medium.",
      idea: "Expand right; shrink left when constraint breaks; track best length. Often a set/map of chars in window.",
      when: "Substring problems, 'longest with at most K distinct', streaming unique checks.",
      syntax: "left = 0\nseen = set()\nbest = 0\nfor right, ch in enumerate(s):\n    while ch in seen:\n        seen.remove(s[left]); left += 1\n    seen.add(ch)\n    best = max(best, right-left+1)",
      code: "def length_of_longest_substring(s):\n    left, best, seen = 0, 0, set()\n    for right, ch in enumerate(s):\n        while ch in seen:\n            seen.remove(s[left]); left += 1\n        seen.add(ch)\n        best = max(best, right - left + 1)\n    return best",
      walkthrough: "'abcabcbb' → window grows abc (3) → shrink on repeats → best 3.",
      bugs: "Forgetting to remove from set when moving left. Infinite while if remove wrong char.",
      resources: [
        { label: "Longest Substring Without Repeating", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/", use: "Practice" },
        { label: "NeetCode sliding window video", url: "https://www.youtube.com/watch?v=wiGpQwVHdE0", use: "Pattern teaching" },
      ],
    },
    stackParen: {
      keys: ["parentheses", "stack", "valid parentheses"],
      why: "Stacks match nesting — compilers, editors, interview staple.",
      idea: "Push openers; on closer, stack top must match; end with empty stack.",
      when: "Bracket validation, parsing, nested structures.",
      syntax: "pairs = {')':'(', ']':'[', '}':'{'}\nstack = []\nfor ch in s:\n    if ch in pairs.values(): stack.append(ch)\n    elif ch in pairs:\n        if not stack or stack[-1] != pairs[ch]: return False\n        stack.pop()\nreturn not stack",
      code: "def is_valid(s):\n    m = {')':'(', ']':'[', '}':'{'}\n    st = []\n    for ch in s:\n        if ch in m.values():\n            st.append(ch)\n        elif ch in m:\n            if not st or st[-1] != m[ch]:\n                return False\n            st.pop()\n    return not st",
      walkthrough: "'([])' pushes ( [ then pops matching. '([)]' fails order.",
      bugs: "Only checking counts not order. Empty stack pop.",
      resources: [
        { label: "Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses/", use: "Solve" },
        { label: "NeetCode Valid Parentheses", url: "https://www.youtube.com/watch?v=WTzjTskDFMg", use: "If stuck" },
      ],
    },
    binarySearch: {
      keys: ["binary search", "binsearch", "lo", "mid"],
      why: "O(log n) on sorted data — interviews and real search.",
      idea: "Maintain lo..hi range that may hold target. Compare mid; throw away half each step.",
      when: "Sorted arrays, search spaces, many Medium 'minimize max' problems later.",
      syntax: "lo, hi = 0, len(nums)-1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if nums[mid] < target: lo = mid + 1\n    elif nums[mid] > target: hi = mid - 1\n    else: return mid\nreturn -1",
      code: "def search(nums, target):\n    lo, hi = 0, len(nums) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if nums[mid] == target: return mid\n        if nums[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1",
      walkthrough: "Write invariant: target is in nums[lo..hi] if present. Update lo/hi without infinite loop.",
      bugs: "mid sticky loops (use lo=mid+1). Overflow mid in other languages. Off-by-one on hi.",
      resources: [
        { label: "Binary Search problem", url: "https://leetcode.com/problems/binary-search/", use: "Solve" },
        { label: "NeetCode Binary Search", url: "https://www.youtube.com/watch?v=s4AKP8M-riQ", use: "Invariant teaching" },
        { label: "Binary search theory notes", url: "https://en.wikipedia.org/wiki/Binary_search_algorithm", use: "Broader concept" },
      ],
    },
    trees: {
      keys: ["invert", "max depth", "level order", "tree", "bfs", "recursion"],
      why: "Trees + recursion are interview core and show up in file systems / UI / ASTs.",
      idea: "Recursive definition: do work on node, recurse left/right. BFS uses a queue for level order.",
      when: "Tree Easy/Mediums, hierarchical data, filesystem-like structures.",
      syntax: "# max depth\ndef max_depth(root):\n    if not root: return 0\n    return 1 + max(max_depth(root.left), max_depth(root.right))\n\n# invert\ndef invert(root):\n    if not root: return None\n    root.left, root.right = invert(root.right), invert(root.left)\n    return root",
      code: "from collections import deque\ndef level_order(root):\n    if not root: return []\n    out, q = [], deque([root])\n    while q:\n        level = []\n        for _ in range(len(q)):\n            n = q.popleft(); level.append(n.val)\n            if n.left: q.append(n.left)\n            if n.right: q.append(n.right)\n        out.append(level)\n    return out",
      walkthrough: "Max depth empty=0. Invert swaps children then recurse. Level order drains queue by layer size.",
      bugs: "Forgetting base case None. Swapping before recurse incorrectly. BFS forgetting layer loop.",
      resources: [
        { label: "Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree/", use: "Recursion warm" },
        { label: "Max Depth", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/", use: "Recursion" },
        { label: "Level Order", url: "https://leetcode.com/problems/binary-tree-level-order-traversal/", use: "BFS" },
        { label: "NeetCode tree intro", url: "https://www.youtube.com/watch?v=OnSn3XEQQYM", use: "Broader trees" },
      ],
    },
    linkedList: {
      keys: ["linked list", "reverse list", "merge two", "list cycle"],
      why: "Pointer manipulation in Python/C form — interviews love it; relates to 216 pointer skills.",
      idea: "Nodes with .next. Reverse with prev/cur/nextTemp. Merge with dummy head. Cycle with set or Floyd.",
      when: "List Easy/Mediums, understanding pointer rewiring.",
      syntax: "prev = None\ncur = head\nwhile cur:\n    nxt = cur.next\n    cur.next = prev\n    prev = cur\n    cur = nxt\nreturn prev",
      code: "class ListNode:\n    def __init__(self, val=0, next=None):\n        self.val, self.next = val, next\n\ndef reverse_list(head):\n    prev, cur = None, head\n    while cur:\n        nxt = cur.next\n        cur.next = prev\n        prev, cur = cur, nxt\n    return prev",
      walkthrough: "Draw 1→2→3. Each step flips one arrow. Dummy head simplifies merge edges.",
      bugs: "Losing next reference before rewiring. Forgetting dummy.next return. Cycle: not advancing pointers.",
      resources: [
        { label: "Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list/", use: "Solve" },
        { label: "Merge Two Sorted Lists", url: "https://leetcode.com/problems/merge-two-sorted-lists/", use: "Dummy head" },
        { label: "Linked List Cycle", url: "https://leetcode.com/problems/linked-list-cycle/", use: "Floyd or set" },
        { label: "NeetCode Reverse List", url: "https://www.youtube.com/watch?v=G0_I-ZF0S38", use: "Visual" },
      ],
    },
    pytest: {
      keys: ["pytest", "test_calc", "unit test"],
      why: "Tests let you change code without fear — required for NetKV protocol and real jobs.",
      idea: "test_*.py functions assert expected behavior. pytest discovers and runs them.",
      when: "Any library/protocol function, CI pipelines, regression bugs.",
      syntax: "# calc.py\ndef add(a, b): return a + b\n\n# test_calc.py\nfrom calc import add\n\ndef test_add():\n    assert add(2, 3) == 5",
      code: "# run:\n# python3 -m pytest -v",
      walkthrough: "Write function → write assert → pytest -v green → change function → broken test teaches you.",
      bugs: "Wrong working directory. Not naming test_*. Assertion rewriting surprises — read failure diff.",
      resources: [
        { label: "pytest getting started", url: "https://docs.pytest.org/en/stable/getting-started.html", use: "Follow exactly" },
        { label: "pytest asserts", url: "https://docs.pytest.org/en/stable/how-to/assert.html", use: "How failures look" },
        { label: "Unit testing explained (video)", url: "https://www.youtube.com/watch?v=1LfxYZ4W6Es", use: "Broader why tests exist" },
      ],
    },
    sockets: {
      keys: ["socket", "echo", "tcp", "accept", "bind", "listen"],
      why: "Networked services are TCP bytes + a protocol you invent. Foundation for NetKV and real backends.",
      idea: "TCP stream: bind/listen/accept then recv/send. Line protocol = messages end with newline. Echo proves the loop.",
      when: "Any custom server, understanding Redis/HTTP at a low level, internship realtime systems intuition.",
      syntax: "import socket\ns = socket.socket()\ns.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)\ns.bind(('127.0.0.1', 6379))\ns.listen()\nconn, addr = s.accept()\ndata = conn.recv(1024)\nconn.sendall(data)",
      code: "# server loop sketch\nwhile True:\n    conn, addr = s.accept()\n    with conn:\n        data = conn.recv(1024)\n        if not data: continue\n        conn.sendall(data)",
      walkthrough: "Start server → client send 'hi\\n' → server echoes → then add parse later.",
      bugs: "Address in use → kill old process. Client hang → no response. Blocking forever → print debug around recv.",
      resources: [
        { label: "Guide: TCP sockets", url: "guides/tcp-sockets-and-protocols.html", use: "Read fully" },
        { label: "Python sockets HOWTO", url: "https://docs.python.org/3/howto/sockets.html", use: "Client/server sections" },
        { label: "socket examples", url: "https://docs.python.org/3/library/socket.html#example", use: "Copy patterns carefully" },
        { label: "TCP explained (video)", url: "https://www.youtube.com/watch?v=PpsEaqJV_4E", use: "Broader networking" },
      ],
    },
    redisKv: {
      keys: ["set/get", "mini-redis", "netkv", "protocol", "ttl", "del"],
      why: "Tiny Redis teaches protocol + state + tests — strong systems story.",
      idea: "Parse text commands into structures; mutate a dict; respond with text. TTL stores expiry timestamps.",
      when: "Systems interviews, caching mental models, product demos.",
      syntax: "def parse(line):\n    parts = line.strip().split()\n    if not parts: raise ValueError('empty')\n    cmd = parts[0].upper()\n    if cmd == 'SET' and len(parts)==3: return ('SET', parts[1], parts[2])\n    if cmd == 'GET' and len(parts)==2: return ('GET', parts[1])\n    raise ValueError('bad command')",
      code: "store = {}\n# SET k v → store[k]=v; return 'OK'\n# GET k → store.get(k, '(nil)')\n# DEL k → store.pop(k, None)",
      walkthrough: "pytest parse first → wire dict in server → SET then GET in client → add DEL/TTL.",
      bugs: "Parsing in the socket loop without tests. Crashing accept loop on bad input. Forgetting newline in responses.",
      resources: [
        { label: "Build Your Own Redis", url: "https://codingchallenges.fyi/challenges/challenge-redis/", use: "Design inspiration" },
        { label: "Redis SET docs", url: "https://redis.io/docs/latest/commands/set/", use: "Real command semantics" },
        { label: "Guide: TCP sockets", url: "guides/tcp-sockets-and-protocols.html", use: "Protocol framing" },
      ],
    },
    git: {
      keys: ["git", "merge conflict", "missing semester git"],
      why: "Daily SWE skill. Conflicts are normal; freezing is not.",
      idea: "commit snapshots; branches diverge; merge combines; conflicts need manual resolution markers.",
      when: "Every project, team work, hackathons.",
      syntax: "git init\ngit add .\ngit commit -m \"message\"\ngit branch feature\ngit switch feature\n# conflict markers: <<<<<<< ======= >>>>>>>",
      code: "# resolve conflict: edit file → remove markers → git add → git commit",
      walkthrough: "Two branches edit same line → merge → fix markers → commit.",
      bugs: "Committing secrets. Force push to shared main. Leaving conflict markers in code.",
      resources: [
        { label: "Missing Semester Git", url: "https://missing.csail.mit.edu/2020/version-control/", use: "Do the exercises" },
        { label: "Git handbook", url: "https://docs.github.com/en/get-started/using-git/about-git", use: "Docs overview" },
        { label: "Merge conflicts docs", url: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts", use: "Conflict specifics" },
      ],
    },
    sql: {
      keys: ["sql", "sqlbolt", "join", "select"],
      why: "Almost every product has a database. SQL is how you ask it questions.",
      idea: "SELECT columns FROM table WHERE filter. JOIN combines tables on keys. GROUP BY aggregates.",
      when: "Backend features, analytics, interview SQL screens, TerpButler DB.",
      syntax: "SELECT name, COUNT(*)\nFROM users u\nJOIN orders o ON o.user_id = u.id\nWHERE o.total > 10\nGROUP BY name;",
      code: "-- practice on SQLBolt interactive lessons",
      walkthrough: "Filter with WHERE → join → aggregate. Read one result set and explain it in English.",
      bugs: "Forgetting JOIN condition (cartesian blowup). Mixing WHERE vs HAVING.",
      resources: [
        { label: "SQLBolt", url: "https://sqlbolt.com/", use: "Do lessons hands-on" },
        { label: "Mode SQL tutorial", url: "https://mode.com/sql-tutorial", use: "Broader SQL" },
        { label: "SQL joins visual (video)", url: "https://www.youtube.com/watch?v=9yeOJ0ZPlrA", use: "Join types" },
      ],
    },
    fastapi: {
      keys: ["fastapi", "uvicorn", "response model", "api route"],
      why: "Modern Python APIs. Matches Gambit-style stacks and intern backend work.",
      idea: "Decorators map HTTP paths to functions. Pydantic models validate/shape JSON.",
      when: "Building APIs, documenting contracts, hackathon backends.",
      syntax: "from fastapi import FastAPI\napp = FastAPI()\n\n@app.get('/health')\ndef health():\n    return {'ok': True}",
      code: "# run: uvicorn main:app --reload\n# open http://127.0.0.1:8000/docs",
      walkthrough: "Create app → write route → run uvicorn → hit /docs → curl JSON.",
      bugs: "Wrong module path for uvicorn. Blocking sync calls in async routes (later topic).",
      resources: [
        { label: "FastAPI first steps", url: "https://fastapi.tiangolo.com/tutorial/first-steps/", use: "Follow tutorial" },
        { label: "Response model", url: "https://fastapi.tiangolo.com/tutorial/response-model/", use: "Typed JSON" },
        { label: "FastAPI intro video", url: "https://www.youtube.com/watch?v=0KS1MHaAIjY", use: "Broader tour" },
      ],
    },
    typescript: {
      keys: ["typescript", "ts basic", "type ", "playground", "any"],
      why: "Types catch bugs before runtime — standard in serious frontend/backends.",
      idea: "Annotate values/functions so illegal data fails at compile time. Avoid any.",
      when: "React/Next codebases, API client types, TerpButler/Gambit UI.",
      syntax: "type Task = { id: string; done: boolean }\nfunction complete(t: Task): Task {\n  return { ...t, done: true }\n}",
      code: "// Try in https://www.typescriptlang.org/play",
      walkthrough: "Define type → write function → intentionally pass wrong shape → read error → fix.",
      bugs: "Using any everywhere. Confusing interface vs type (both fine early).",
      resources: [
        { label: "TS Basic Types", url: "https://www.typescriptlang.org/docs/handbook/2/basic-types.html", use: "Read + try" },
        { label: "TypeScript Playground", url: "https://www.typescriptlang.org/play", use: "Experiment" },
        { label: "TS in 5 min (video)", url: "https://www.youtube.com/watch?v=zQnAVlEaP8w", use: "Quick overview" },
      ],
    },
    docker: {
      keys: ["docker", "dockerfile", "container", "image"],
      why: "Same app runs the same way on other machines — demos and deploy.",
      idea: "Dockerfile builds an image (filesystem + start command). Container is a running instance.",
      when: "Shipping NetKV/Gambit demos, internships, hackathon judging machines.",
      syntax: "FROM python:3.11-slim\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nCMD [\"python\", \"server_kv.py\"]\n\n# docker build -t netkv .\n# docker run --rm -p 6379:6379 netkv",
      code: "# Keep Dockerfile next to your app; document ports in README",
      walkthrough: "Write Dockerfile → build → run → hit from host client → fix COPY paths if fail.",
      bugs: "Wrong workdir. Forgetting EXPOSE/docs for ports. Huge context from copying node_modules (use .dockerignore).",
      resources: [
        { label: "Docker Get Started", url: "https://docs.docker.com/get-started/", use: "Modules 1-2" },
        { label: "Build an image", url: "https://docs.docker.com/get-started/docker-concepts/building-images/build-an-image/", use: "Dockerfile concepts" },
        { label: "Docker video overview", url: "https://www.youtube.com/watch?v=Gjnup-PuquQ", use: "Broader mental model" },
      ],
    },
    actions: {
      keys: ["github actions", "ci.yml", "workflow", "actions"],
      why: "CI runs tests on every push — team maturity signal.",
      idea: "YAML workflow: checkout code → setup language → install → pytest.",
      when: "Any shared repo, preventing broken main.",
      syntax: "name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with: { python-version: '3.11' }\n      - run: pip install -r requirements.txt pytest\n      - run: pytest -q",
      code: "# place at .github/workflows/ci.yml",
      walkthrough: "Add file → push → Actions tab → green check → break a test → see red → fix.",
      bugs: "Wrong paths. Missing requirements. Testing locally different Python version.",
      resources: [
        { label: "Actions quickstart", url: "https://docs.github.com/en/actions/writing-workflows/quickstart", use: "Follow + adapt" },
        { label: "setup-python action", url: "https://github.com/actions/setup-python", use: "Exact versions" },
      ],
    },
    ostep: {
      keys: ["ostep", "process", "virtual memory", "address space"],
      why: "OS vocabulary for 216 and systems interviews.",
      idea: "OS virtualizes CPU/memory. A process is a running program with its own abstractions. Address spaces isolate memory.",
      when: "216 lectures, explaining segfaults, concurrency later.",
      syntax: "# conceptual — read PDFs; take notes as definitions + examples",
      code: "# optional demo later: fork/exec on Unix (course dependent)",
      walkthrough: "Read chapter → write definitions in your words → connect to a bug you have seen.",
      bugs: "Passive highlighting without retrieval. Fix: close PDF and rewrite 5 terms.",
      resources: [
        { label: "OSTEP book", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/", use: "Free textbook hub" },
        { label: "OSTEP intro PDF", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/intro.pdf", use: "Start here" },
        { label: "OSTEP CPU intro", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/cpu-intro.pdf", use: "Processes" },
        { label: "OSTEP VM intro", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/vm-intro.pdf", use: "Address spaces" },
        { label: "OS concepts overview (video)", url: "https://www.youtube.com/watch?v=vBURBt_ZQZ4", use: "Broader intro" },
      ],
    },
    make: {
      keys: ["makefile", "multi-file", "make clean"],
      why: "216 projects grow past one .c file. Make rebuilds only what changed.",
      idea: "Targets + dependencies + recipe lines (tab-indented). Headers declare; .c defines.",
      when: "Multi-file C projects, any repeatable build.",
      syntax: "CC=gcc\nCFLAGS=-Wall -Wextra -g\napp: main.o util.o\n\t$(CC) $(CFLAGS) -o app main.o util.o\n\nclean:\n\trm -f *.o app",
      code: "/* util.h */\nint add(int a, int b);\n/* util.c */\nint add(int a, int b) { return a+b; }",
      walkthrough: "Split helper → write Makefile → make → run → make clean.",
      bugs: "Spaces instead of tabs in recipes. Missing header deps causing stale builds.",
      resources: [
        { label: "GNU Make intro", url: "https://www.gnu.org/software/make/manual/html_node/Introduction.html", use: "Concepts" },
        { label: "Makefile tutorial", url: "https://makefiletutorial.com/", use: "Practical patterns" },
      ],
    },
    codebase: {
      keys: ["gambit", "api entry", "codebase", "architecture", "terpbutler", "oral", "path"],
      why: "Owning products beats listing them. Interviews and hackathons test this.",
      idea: "Chase one user behavior through UI → API → data/model. Write hops file::function. Prove an intermediate value.",
      when: "Every project defense, internship onboarding, hackathon base work.",
      syntax: "# note format\n1. web/.../Page.tsx onClick\n2. GET /predict\n3. api/routes/predict.py handler\n4. models/elo.py compute()\n5. JSON response",
      code: "# temporary proof\nprint('features', features[:5])\n# or assert score >= 0",
      walkthrough: "Boot → pick feature → search route → number hops → print one value → document.",
      bugs: "Reading every file. Getting lost in dependencies. Claiming ML you cannot explain.",
      resources: [
        { label: "Guide: Reading a codebase", url: "guides/reading-a-codebase.html", use: "Method" },
        { label: "Gambit repo", url: "https://github.com/abhyvx/Gambit", use: "Your product" },
        { label: "TerpButler repo", url: "https://github.com/abhyvx/TerpButler", use: "Campus product" },
        { label: "How to demo (YC)", url: "https://www.ycombinator.com/library/8g-how-to-demo", use: "Demo craft" },
      ],
    },
    star: {
      keys: ["star", "bullet", "brag", "behavioral", "application", "resume", "internship_closeout", "evidence"],
      why: "Skills without stories do not convert to offers. Capture real work accurately.",
      idea: "STAR: Situation, Task, Action, Result. Bullets = contribution + skill, tied to artifacts.",
      when: "Intern apps, behavioral interviews, performance notes.",
      syntax: "S: ...\nT: ...\nA: what YOU did (tools, decisions)\nR: outcome (honest)",
      code: "# EVIDENCE.md\n# Bullet → artifact path/URL",
      walkthrough: "Pick real AIQuest debug → write S/T/A/R → speak 90s → trim fluff.",
      bugs: "Fake metrics. Team 'we' with no personal action. Stories you cannot defend.",
      resources: [
        { label: "STAR method", url: "https://www.themuse.com/advice/star-interview-method", use: "Structure" },
        { label: "Behavioral interview guide", url: "https://www.techinterviewhandbook.org/behavioral-interview-questions/", use: "Question bank" },
      ],
    },
    dp: {
      keys: ["climbing stairs", "house robber", "dp", "dynamic"],
      why: "DP is interview Medium territory: overlapping subproblems + optimal substructure.",
      idea: "Define recurrence first. climbing stairs: dp[i]=dp[i-1]+dp[i-2].",
      when: "1D DP problems, path counting, optimization over sequences.",
      syntax: "def climb(n):\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n+1):\n        a, b = b, a+b\n    return b",
      code: "# always write recurrence in a comment before coding",
      walkthrough: "n=1→1, n=2→2, n=3→3, n=4→5. Build bottom-up.",
      bugs: "Coding before recurrence. Off-by-one indexing.",
      resources: [
        { label: "Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs/", use: "Solve" },
        { label: "House Robber", url: "https://leetcode.com/problems/house-robber/", use: "Next 1D DP" },
        { label: "NeetCode DP intro", url: "https://www.youtube.com/watch?v=oBt53YbR9Kk", use: "Broader DP" },
      ],
    },
    aws: {
      keys: ["nextwork", "aws", "free tier", "cloud"],
      why: "Cloud literacy is expected. Finished writeups beat console tourism.",
      idea: "Follow a guided project; write services used, what you built, cost; delete unused resources.",
      when: "Portfolio cloud signal, internships touching AWS.",
      syntax: "# operational checklist\n# 1 create resources via tutorial\n# 2 document\n# 3 set billing alarm mindset\n# 4 delete when done",
      code: "# ~/umd-prep/aws/project-01.md structure:\n# Services | Architecture | Steps | Cost | Cleanup",
      walkthrough: "Account → tutorial → build → writeup → cleanup.",
      bugs: "Leaving instances running. No writeup = no resume value.",
      resources: [
        { label: "NextWork roadmaps", url: "https://www.nextwork.org/roadmaps/", use: "Guided projects" },
        { label: "AWS Free Tier", url: "https://aws.amazon.com/free/", use: "Cost boundaries" },
        { label: "AWS for Newbies video", url: "https://www.youtube.com/watch?v=hUFmu9Vjukw", use: "Orientation" },
      ],
    },
    shell: {
      keys: ["shell", "bash", "pipes", "missing semester shell"],
      why: "CLI fluency compounds in 216, servers, and debugging.",
      idea: "Programs compose with pipes. stdout→stdin. Scripts automate repetition.",
      when: "Log grepping, batch files, deploy scripts.",
      syntax: "ls | grep \".c$\" | wc -l\necho 'hi' > out.txt\ncat out.txt",
      code: "#!/bin/bash\nset -euo pipefail\ncd \"$HOME/umd-prep\" && ls",
      walkthrough: "Run a pipe → write a 5-line script → chmod +x → run.",
      bugs: "Spaces in paths unquoted. Missing execute bit.",
      resources: [
        { label: "Missing Semester Shell", url: "https://missing.csail.mit.edu/2020/shell-tools/", use: "Do exercises" },
        { label: "Bash guide", url: "https://guide.bash.academy/", use: "Broader shell" },
      ],
    },
    math241: {
      keys: ["math 241", "integral", "calc", "u-sub"],
      why: "GPA track. Technique blocks beat cramming.",
      idea: "Identify technique (u-sub, parts, series) then execute carefully.",
      when: "Weekly homework/exams.",
      syntax: "# show each algebra step; box the final answer",
      code: "# not code — worked paper problems",
      walkthrough: "Pick 5 problems → timer → check solutions → redo misses.",
      bugs: "Arithmetic slips. Skipping justification.",
      resources: [
        { label: "Paul Calc II notes", url: "https://tutorial.math.lamar.edu/Classes/CalcII/CalcII.aspx", use: "Technique reference" },
        { label: "3Blue1Brown Essence of Calc", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr", use: "Intuition" },
      ],
    },
    neetcodePractice: {
      keys: ["from blank", "neetcode", "review", "medium", "tournament", "practice"],
      why: "Retrieval practice is how interview skill sticks.",
      idea: "Close notes. Timed attempt. Log misses. Revisit weak patterns.",
      when: "Weekly forever until interviews end.",
      syntax: "# session template\n# 1 pick pattern\n# 2 25-45 min attempt\n# 3 write miss reason\n# 4 redo in 48h",
      code: "# save solutions under ~/umd-prep/dsa/ with Big-O comments",
      walkthrough: "Blank file → think aloud → code → test → only then watch video if failed.",
      bugs: "Watching solutions first. Not logging misses.",
      resources: [
        { label: "NeetCode 150", url: "https://neetcode.io/practice", use: "Problem set" },
        { label: "NeetCode roadmap", url: "https://neetcode.io/roadmap", use: "Order" },
        { label: "How to practice LC (video)", url: "https://www.youtube.com/watch?v=KIr6at1b9QU", use: "Method" },
      ],
    },
  },
};
